#[derive(Debug, PartialEq)]
pub enum ParseError {
    ExpectedObject,
    TypeStringMissing,
    NotImplemented,
    InvalidTypeString,
    StructureHasNoMembers,
    InvalidStructureMembers,
    MissingListShape,
    InvalidListShape,
    MissingListMember,
    InvalidListMember,
    InvalidMember(String),
    InvalidRequired,
    MissingErrorInException,
    InvalidMaxInteger,
    InvalidMinInteger,
    InvalidStringMax,
    InvalidStringMin,
    InvalidStringPattern,
    InvalidStringEnum,
    InvalidStringVariant,
    ServiceDefinitionMissingShapes,
    ServiceDefinitionInvalidShapes,
    SerdeError,
}
